package com.sarrawi.tts
//
//import android.os.Bundle
//import android.speech.tts.TextToSpeech
//import androidx.appcompat.app.AppCompatActivity
//import androidx.recyclerview.widget.DiffUtil
//import androidx.recyclerview.widget.LinearLayoutManager
//import androidx.recyclerview.widget.RecyclerView
//import java.util.Locale
//
//class MainActivity2 : AppCompatActivity(), TextToSpeech.OnInitListener {
//
//    private lateinit var tts: TextToSpeech
//    private lateinit var recyclerView: RecyclerView
//    private lateinit var adapter: WordAdapter
//    private var wordList = mutableListOf<Pair<String, String>>()
//    private var oldList = wordList.toList() // لحفظ القائمة القديمة
//
//    override fun onCreate(savedInstanceState: Bundle?) {
//        super.onCreate(savedInstanceState)
//        setContentView(R.layout.activity_main2)
//
//        recyclerView = findViewById(R.id.recyclerView)
//        tts = TextToSpeech(this, this)
//
//        recyclerView.layoutManager = LinearLayoutManager(this)
//        adapter = WordAdapter(this, wordList, tts)
//        recyclerView.adapter = adapter
//
//        // تحميل البيانات
//        loadData()
//    }
//
//    private fun loadData() {
//        val newList = mutableListOf<Pair<String, String>>()
//        newList.add("Word " to "معنى ")
//
//        val wordList = listOf(
//            "Hello" to "مرحبا",
//            "Goodbye" to "وداعا",
//            "Thank you" to "شكرا"
//            // أضف المزيد من الكلمات والمعاني هنا
//        )
//        // استخدام DiffUtil لتحديث RecyclerView
//        val diffCallback = WordDiffCallback(oldList, newList)
//        val diffResult = DiffUtil.calculateDiff(diffCallback)
//
//        wordList = newList
//        diffResult.dispatchUpdatesTo(adapter)
//        oldList = newList // تحديث القائمة القديمة
//    }
//
//    override fun onInit(status: Int) {
//        if (status == TextToSpeech.SUCCESS) {
//            tts.language = Locale.US
//        }
//    }
//
//    override fun onDestroy() {
//        if (::tts.isInitialized) {
//            tts.stop()
//            tts.shutdown()
//        }
//        super.onDestroy()
//    }
//}
//



import android.os.Bundle
import android.speech.tts.TextToSpeech
import androidx.appcompat.app.AppCompatActivity
import androidx.recyclerview.widget.GridLayoutManager
import androidx.recyclerview.widget.RecyclerView
import java.util.Locale
import androidx.recyclerview.widget.LinearLayoutManager


class MainActivity2 : AppCompatActivity(), TextToSpeech.OnInitListener {

    private lateinit var tts: TextToSpeech
    private lateinit var recyclerView: RecyclerView
    val wordList = mutableListOf<Pair<String, String>>()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main2)

        recyclerView = findViewById(R.id.recyclerView)

        tts = TextToSpeech(this, this)

//        val wordList = listOf(
//            "Hello" to "مرحبا",
//            "Goodbye" to "وداعا",
//            "Thank you" to "شكرا"
//            // أضف المزيد من الكلمات والمعاني هنا
//        )

        arrayList()

        // إعداد LinearLayoutManager بدلاً من GridLayoutManager
        val layoutManager = LinearLayoutManager(this)
        recyclerView.layoutManager = layoutManager

        val adapter = WordAdapter(this, wordList, tts)
        recyclerView.adapter = adapter
    }

    override fun onInit(status: Int) {
        if (status == TextToSpeech.SUCCESS) {
            tts.language = Locale.US
        }
    }

    override fun onDestroy() {
        if (::tts.isInitialized) {
            tts.stop()
            tts.shutdown()
        }
        super.onDestroy()
    }

    fun arrayList(){

        wordList.add("Word " to "معنى ")
        wordList.add("Countryside"  to " الريف" )
        wordList.add("Hill"         to " تل" )
        wordList.add("Mountain"     to "جبل" )
        wordList.add("Valley"       to "وادي" )
        wordList.add("Wood"         to "خشب" )
        wordList.add("Forest"       to "غابة" )
        wordList.add("Copse"        to "الشجر الكثير الملتف, الأيكة" )
        wordList.add("Field"        to "حقل" )
        wordList.add("Meadow"       to "مرج" )
        wordList.add("Plain"        to "سهل" )
        wordList.add("Moor"         to "أرض بور" )
        wordList.add("Bog"          to "بركة, مستنقع" )
        wordList.add("Swamp"        to "مستنقع" )
        wordList.add("Hedge"        to "سياج من الشجيرات" )
        wordList.add("Path"         to "مسار, ممر" )
        wordList.add("Fence"        to "سور, سياج" )
        wordList.add("Wall"         to "حائط" )
        wordList.add("Ditch"        to "خندق" )
        wordList.add("Gate"         to "بوابة" )
        wordList.add("Farm"         to "مزرعة" )
        wordList.add("Bridge"       to "جسر، كوبري" )
        wordList.add("Desert"       to "صحراء" )
        wordList.add("Glacier"      to "نهر الجليد" )
        wordList.add("Jungle"       to "دغل  مفرد أدغال " )
        wordList.add("Rainforest"   to "غابة   مطيرة" )
        wordList.add("Volcano"         to "بركان" )
        wordList.add("Stream"          to "تيّارمائي" )
        wordList.add("River"           to "نهر" )
        wordList.add("Canal"           to "قناة" )
        wordList.add("Pond"            to "بركة" )
        wordList.add("Lake"            to "بحيرة" )
        wordList.add("Reservoir"       to "خزان، صهريج" )
        wordList.add("Waterfall"       to " شلال" )
        wordList.add("Well"            to "حسنا" )
        wordList.add("Dam"             to "سد" )
        wordList.add("Power station"   to "محطة كهرباء" )
        wordList.add("Wind farm"       to "مزرعة   الرياح" )
        wordList.add("Mine"            to "منجم" )
        wordList.add("Quarry"          to "مقلع الحجارة" )
        wordList.add("Agriculture"     to "زراعة" )
        wordList.add("Barn"            to "حظيرة" )
        wordList.add("Ranch"           to "مزرعة" )
        wordList.add("Crop"            to "محصول" )
        wordList.add("Harvest"         to "حصاد" )
        wordList.add("Hay"             to "قش – تبن" )
        wordList.add("Wheat"           to "قمح" )
        wordList.add("Irrigation"      to "ري - سقي" )
        wordList.add("Livestock"       to "ماشية" )
        wordList.add("Plough"          to "حرث" )
        wordList.add("Reaping"         to "حصد - جني" )
        wordList.add("Ocean"              to "محيط" )
        wordList.add("Sea"                to "بحر" )
        wordList.add("Shore – Coast"      to "ساحل" )
        wordList.add("Beach"              to "شاطئ" )
        wordList.add("Cliff"              to "جرف - منحدر" )
        wordList.add("Island"             to "جزيرة" )
        wordList.add("Peninsula"          to "شبه الجزيرة" )
        wordList.add("Rock"               to "صخرة" )
        wordList.add("Tide"               to "مد و جزر" )
        wordList.add("Wave"               to "موج" )
        wordList.add("Pier"               to "رصيف بحري" )
        wordList.add("Lighthouse"         to "منارة" )
        wordList.add("Harbour"            to "ميناء" )
        wordList.add("Oil rig"            to "جهاز الحفر النفطي" )
        wordList.add("Country"            to "بلد" )
        wordList.add("City"               to "مدينة" )
        wordList.add("Town"               to "بلدة" )
        wordList.add("Village"            to "قرية" )
        wordList.add("Eruption"           to "ثوران" )
        wordList.add("Earthquake"         to "زلزال" )
        wordList.add("Tsunami"            to "إعصار بحري" )
        wordList.add("Avalanche"          to "انهيار جليدي" )
        wordList.add("Landslide"                to "إنهيار ارضي" )
        wordList.add("Lava"                     to "حمم" )
        wordList.add("Capital  - Capital city"  to "عاصمة" )
        wordList.add("Border"          to "حدود" )
        wordList.add("Nationalpark"    to "حديقة وطنية" )
        wordList.add("Northpole"       to "القطب الشمالي" )
        wordList.add("Southpole"       to "القطب الجنوبي" )
        wordList.add("Equator"         to "خط الاستواء" )
        wordList.add("Longitude"       to "خط الطول" )
        wordList.add("Latitude"        to "خط العرض" )
        wordList.add("Sealevel"        to "مستوى سطح البحر" )
        wordList.add("Erosion"         to "تآكل – تعرية" )
        wordList.add("Pollution"       to "تلوث" )
        wordList.add("Atmosphere"      to "الغلاف الجوي" )
        wordList.add("Environment"     to "بيئة" )
        wordList.add("Population"      to "عدد السكان" )
        wordList.add("Famine"          to "مجاعة" )
        wordList.add("Fossil fuel"     to "الوقود الأحفوري" )
        wordList.add("Energy"          to "طاقة" )
        wordList.add("Unemployment"    to "بطالة" )
        wordList.add("Landscape"       to "مشهد – منظر طبيعي" )
        wordList.add("Literacy"        to "محو الأمية" )
        wordList.add("Malnutrition"    to "سوء التغذية" )
        wordList.add("Migration"       to "هجرة" )
        wordList.add("Radiation"      to "إشعاع" )
        wordList.add("Nuclear energy" to "طاقة نووية" )
        wordList.add("Crater"         to "فوهة البركان" )
        wordList.add("Sand dunes"     to "الكثبان الرملية" )
        wordList.add("Trade" to "تجارة")
        wordList.add("Urban" to "حضري")
        wordList.add("Rural" to "قروي – ريفي")
        wordList.add("Economy" to "اقتصاد")
        wordList.add("Poverty" to "فقر")
        wordList.add("Slum" to "أحياء فقيرة")
        wordList.add("Life expectancy" to "متوسط العمر المتوقع")
        wordList.add("Attic" to "غرفة علوية، سندرة")
        wordList.add("Bathroom" to "حمّام")
        wordList.add("Bedroom" to "غرفة النوم")
        wordList.add("Cellar" to "سرداب")
        wordList.add("Conservatory" to "معهد الموسيقى")
        wordList.add("Dining room" to "غرفة الطعام")
        wordList.add("Hall" to "صالة")
        wordList.add("Kitchen" to "مطبخ")
        wordList.add("ground floor" to "الطابق الارضي")
        wordList.add("Lavatory" to "مرحاض")
        wordList.add("Livingroom" to "غرفة المعيشة")
        wordList.add("Loft" to "غرفة علوية")
        wordList.add("Lounge" to "غرفة الاستقبال")
        wordList.add("Shower room" to "غرفة استحمام")
        wordList.add("Study" to "دراسة")
        wordList.add("Sitting room" to "غرفة الجلوس")
        wordList.add("Toilet" to "مرحاض) تواليت(")
        wordList.add("Utility room" to "غرفة المرافق")
        wordList.add("Wc" to "مرحاض – دورة مياه")
        wordList.add("Backdoor" to "الباب الخلفي")
        wordList.add("Bath" to "حمام")
        wordList.add("Ceiling" to "سقف")
        wordList.add("Central heating" to "التدفئة المركزية")
        wordList.add("Chimney" to "مدخنة")
        wordList.add("Door" to "باب")
        wordList.add("Doorbell" to "جرس")
        wordList.add("Drainpipe" to "أنبوب التصريف")
        wordList.add("Double glazing" to "زجاج مزدوج")
        wordList.add("Fireplace" to "موقد- مدفأة")
        wordList.add("Floor" to "أرضية")
        wordList.add("Frontdoor" to "الباب الامامي")
        wordList.add("Guttering" to "مزراب")
        wordList.add("Roof" to "سطح")
        wordList.add("Shower" to "استحمام – دش")
        wordList.add("Stairs" to "درج")
        wordList.add("Staircase" to "سُّلّم")
        wordList.add("Window" to "نافذة")
        wordList.add("Downstairs" to "طابق سفلي")
        wordList.add("Upstairs" to "طابق علوي")
        wordList.add("Gas bill" to "فاتورة الغاز")
        wordList.add("Electricity bill" to "فاتورة الكهرباء")
        wordList.add("Telephone bill" to "فاتورة الهاتف")
        wordList.add("Water bill" to "فاتورة الماء")
        wordList.add("Chores" to "الأعمال المنزلية")
        wordList.add("The backgarden" to "الحديقة الخلفية")
        wordList.add("Clothesline" to "حبل الغسيل")
        wordList.add("Drain" to "مصرف مياه ) بالوعة (")
        wordList.add("Drive" to "قيادة أو محرك")
        wordList.add("Dustbin" to "صندوق القمامة")
        wordList.add("A basket of flowers" to "سلة من الزهور")
        wordList.add("Flowerpot" to "إناء الزهور- أصيص")
        wordList.add("Flowers" to "زهور")
        wordList.add("The frontgarden" to "الحديقة الأمامية")
        wordList.add("Garage" to "مرآب، جراج")
        wordList.add("Lawn furniture" to "أثاث الحديقة")
        wordList.add("Gate" to "بوابة")
        wordList.add("Gravel" to "حصى")
        wordList.add("Greenhouse" to "بيت زجاجي، صوبة زراعية")
        wordList.add("Hanging basket" to "سلة معلقة")
        wordList.add("Hedge" to "سياج")
        wordList.add("Lawn" to "بستان")
        wordList.add("Letterbox" to "صندوق الرسائل")
        wordList.add("Logs" to "جذوع الأشجار")
        wordList.add("Orchard" to "بستان")
        wordList.add("Path" to "طريق")
        wordList.add("Patio" to "فناء – باحة")
        wordList.add("Plants" to "نباتات")
        wordList.add("Pond" to "بركة")
        wordList.add("Shed" to "كوخ – سقيفة")
        wordList.add("Pool" to "بركة سباحة")
        wordList.add("Swing" to "أرجوحة")
        wordList.add("Trampoline" to "منصة القفز")
        wordList.add("Vegetablegarden" to "حديقة خضروات")
        wordList.add("Weeds" to "الأعشاب الضارة")
        wordList.add("Mow the lawn" to "جّزّالعشب – قص العشب")
        wordList.add("Axe" to "فأس")
        wordList.add("Fork" to "شوكة")
        wordList.add("Rake" to "مجرفة – أداة لجمع العشب")
        wordList.add("Hosepipe" to "خرطوم سقاية")
        wordList.add("Lawnmower" to "جزارة عشب")
        wordList.add("Hoe" to "مجرفة")
        wordList.add("Scissors" to "مقص")
        wordList.add("Shears" to "مقص الزرع")
        wordList.add("Spade" to "مجرفة – مجراف")
        wordList.add("Trowel" to "جاروف")
        wordList.add("Watering can" to "رشاش مياه")
        wordList.add("Wheelbarrow" to "عربة يدوية")
        wordList.add("Fridge – Refrigerator" to "ثلاجة – بَرّاد")
        wordList.add("Coffee pot" to "وعاء القهوة")
        wordList.add("Cooker" to "جهاز طبخ")
        wordList.add("Dishwasher" to "غسالة صحون")
        wordList.add("Freezer" to "مجمد")
        wordList.add("Kettle" to "غلاية")
        wordList.add("Oven" to "فرن")
        wordList.add("Stove" to "موقد")
        wordList.add("Toaster" to "محمصة خبز")
        wordList.add("Washing machine" to "غسالة")
        wordList.add("Bottle opener" to "فّتّاحة زجاجات")
        wordList.add("Chopping board" to "لوح التقطيع – لوح فرم")
        wordList.add("Colander" to "مصفاة")
        wordList.add("Corkscrew" to "مفتاح")
        wordList.add("Frying pan" to "مقلاة")
        wordList.add("Cheese grater" to "مبشرة جبن")
        wordList.add("Juicer" to "عصارة")
        wordList.add("Tinfoil" to "رقائق القصدير")
        wordList.add("Kitchenscales" to "ميزان المطبخ")
        wordList.add("Ladle" to "مغرفة")
        wordList.add("Mixing bowl" to "وعاء خلط")
        wordList.add("Evidence" to "إثبات - دليل")
        wordList.add("Ovengloves" to "قفازات الفرن")
        wordList.add("Rollingpin" to "مرقاق العجين")
        wordList.add("Saucepan" to "ِقِدر الحساء")
        wordList.add("Sponge" to "إسفنجة")
        wordList.add("Sieve" to "مُنخل – غربال")
        wordList.add("Tin opener" to "فتاحة علب")
        wordList.add("Tongs" to "ملقط")
        wordList.add("Tray" to "صينية")
        wordList.add("Whisk" to "مخفقة بيض")
        wordList.add("Wooden spoon" to "ملعقة خشب")
        wordList.add("Knife" to "سكين")
        wordList.add("Fork" to "شوكة")
        wordList.add("Spoon" to "ملعقة")
        wordList.add("Dessert spoon" to "ملعقة الحلوى")
        wordList.add("Soup spoon" to "ملعقة الحساء")
        wordList.add("Tablespoon" to "ملعقة الطعام")
        wordList.add("Teaspoon" to "ملعقة الشاي")
        wordList.add("Steak knife" to "سكين لحم")
        wordList.add("Chopsticks" to "عيدان الطعام")
        wordList.add("Cup" to "كوب – فنجان")
        wordList.add("Bowl" to "زبدية , سلطانية")
        wordList.add("Crockery" to "آنية فّخّارية")
        wordList.add("Glass" to "كأس زجاجي")
        wordList.add("Jar" to "جرّة")
        wordList.add("Jug" to "إبريق")
        wordList.add("Mug" to "كوز – قدح")
        wordList.add("Plate" to "طبق")
        wordList.add("Saucer" to "طبق الفنجان")
        wordList.add("Sugarbowl" to "وعاء السكر – سّكّريّة")
        wordList.add("Teapot" to "إبريق الشاي")
        wordList.add("Wineglass" to "كأس خمر")
        wordList.add("Bin" to "صندوق")
        wordList.add("Clear plastic" to "بلاستيك شفاف")
        wordList.add("Cookbook" to "كتاب الطبخ")
        wordList.add("Dishcloth" to "ليفة الصحون")
        wordList.add("Sink" to "مغسلة – حوض المطبخ")
        wordList.add("Grill" to "شواية")
        wordList.add("Kitchen table" to "طاولة المطبخ")
        wordList.add("Plug" to "سدادة")
        wordList.add("Tea Towel" to "منشفة الشاي")
        wordList.add("Shelf" to "رف")
        wordList.add("Towel rack" to "حامل مناشف")
        wordList.add("Tablecloth" to "مفرش الطاولة")
        wordList.add("Washing up liquid" to "سائل غسل الصحون")
        wordList.add("Wash" to "يغسل")
        wordList.add("Wash the dishes" to "يغسل الصحون")
        wordList.add("Cleans the table" to "ينظف الطاولة")
        wordList.add("Set the table" to "يجهز الطاولة")
        wordList.add("Armchair" to "كرسي ذو ذراعين")
        wordList.add("Bed" to "سرير")
        wordList.add("Bedside table" to "طاولة السرير")
        wordList.add("Bookcase" to "خزانة كتب")
        wordList.add("Bookshelf" to "رف للكتب")
        wordList.add("Chair" to "كرسي")
        wordList.add("Chest of drawers" to "خزانة الأدراج")
        wordList.add("Clock" to "ساعة حائط")
        wordList.add("Coat rack" to "رف المعطف – شمّاعة")
        wordList.add("Coffee table" to "طاولة صغيرة")
        wordList.add("Cupboard" to "خزانة – دولاب")
        wordList.add("Desk" to "مكتب – منضدة")
        wordList.add("Double bed" to "سرير مزدوج")
        wordList.add("Dressing table" to "طاولة الزينة")
        wordList.add("Double room" to "غرفة مزدوجة")
        wordList.add("Filing cabinet" to "خزانة الملفات")
        wordList.add("Mirror" to "مرآة")
        wordList.add("Piano" to "بيانو")
        wordList.add("Sideboard" to "بوفيه")
        wordList.add("Single bed" to "سرير مفرد")
        wordList.add("Sofa" to "أريكة – كنبة")
        wordList.add("Sofa bed" to "أريكة يمكن تحويلها إلى سرير")
        wordList.add("Stool" to "مقعد")
        wordList.add("Table" to "طاولة")
        wordList.add("Wardrobe" to "خزانة الملابس")
        wordList.add("Alarm clock" to "ساعة المنبه")
        wordList.add("Bathroom scales" to "ميزان الحمام")
        wordList.add("Blue-Ray player" to "جهاز تشغيل أقراص ليزرية")
        wordList.add("CD player" to "جهاز تشغيل سي دي")
        wordList.add("DVD player" to "قارئ أقراص دي في دي")
        wordList.add("Electric stove" to "موقد كهربائي – فرن كهربائي")
        wordList.add("Games console" to "وحدة التحكم في الألعاب")
        wordList.add("Gas stove" to "موقد الغاز")
        wordList.add("Vacuum cleaner" to "مكنسة كهربائية")
        wordList.add("Iron" to "مكواة")
        wordList.add("Lamp" to "مصباح")
        wordList.add("Radiator" to "مشعاع – مدفأة")
        wordList.add("Radio" to "مذياع – راديو")
        wordList.add("Record player" to "مشغل أسطوانات")
        wordList.add("Spin dryer" to "نشّافة , مجفف ملابس")
        wordList.add("Stereo" to "جهاز تكبير الصوت")
        wordList.add("Telephone" to "تلفون – هاتف")
        wordList.add("Television" to "تلفاز")
        wordList.add("Washing machine" to "غسالة كهربائية")
        wordList.add("Blanket" to "غطاء – بطانية")
        wordList.add("Blinds" to "ستائر")
        wordList.add("Carpet" to "سجادة")
        wordList.add("Curtains" to "ستائر")
        wordList.add("Cushion" to "وسادة")
        wordList.add("Duvet" to "لحاف")
        wordList.add("Mattress" to "ِفِراش – مرتبة")
        wordList.add("Pillow" to "وسادة - مخدة")
        wordList.add("Pillowcase" to "غطاء الوسادة")
        wordList.add("Rug" to "بساط")
        wordList.add("Sheet" to "صفحة – ورقة")
        wordList.add("Tablecloth" to "مفرش المائدة")
        wordList.add("Towel" to "منشفة")
        wordList.add("Wallpaper" to "ورق جدران - ورق الحائط")
        wordList.add("Bath" to "مغطس – بانيو")
        wordList.add("Bin" to "سلة مهملات")
        wordList.add("Broom" to "مكنسة – مقشة")
        wordList.add("Bucket" to "سطل – دلو")
        wordList.add("Coat hanger" to "شمّاعة المعاطف")
        wordList.add("Cold tap" to "صنبور الماء البارد")
        wordList.add("Doorhandle" to "مقبض الباب")
        wordList.add("Doorknob" to "مقابض الأبواب")
        wordList.add("Doormat" to "ممسحة الأرجل")
        wordList.add("Dustbin" to "صندوق القمامة")
        wordList.add("Dustpan and brush" to "مكنسة وجاروف")
        wordList.add("Flannel" to "الفانيلا")
        wordList.add("Fuse box" to "صندوق الكهرباء")
        wordList.add("Hot tap" to "صنبور الماء الساخن")
        wordList.add("House plant" to "نبات منزلي")
        wordList.add("Ironing board" to "طاولة الكيّ")
        wordList.add("Lamp shade" to "مظلة المصباح")
        wordList.add("Light switch" to "مفتاح ضوء كهرباء")
        wordList.add("Mop" to "ممسحة")
        wordList.add("Ornament" to "زينة – زخرفة")
        wordList.add("Painting" to "لوحة")
        wordList.add("Picture" to "صورة")
        wordList.add("Power socket" to "مأخذ او مقبس الكهرباء")
        wordList.add("Drain" to "بالوعة")
        wordList.add("Poster" to "مُلصق")
        wordList.add("Sponge" to "إسفنج")
        wordList.add("Tap" to "صنبور - حنفية")
        wordList.add("Torch" to "شعلة")
        wordList.add("Vase" to "مزهرية")
        wordList.add("Wastepaper basket" to "سلة النفايات الورقية")
        wordList.add("Battery" to "بطارية")
        wordList.add("Candle" to "شمعة")
        wordList.add("Cotton" to "قطن")
        wordList.add("Envelope" to "ظرف")
        wordList.add("Fireplace" to "شعلة للغاز أو المدفأة")
        wordList.add("Fuse" to "فتيل")
        wordList.add("Glue" to "غراء أو صمغ")
        wordList.add("Light bulb" to "مصباح أو لمبة")
        wordList.add("Lighter" to "شعلة أو قداحة")
        wordList.add("Match" to "كبريت")
        wordList.add("Needle" to "إبرة")
        wordList.add("Pin" to "دبوس")
        wordList.add("Scissors" to "مقص")
        wordList.add("Sellotape" to "شريط لاصق")
        wordList.add("Stamps" to "طوابع")
        wordList.add("Pen" to "قلم")
        wordList.add("Pencil" to "قلم رصاص")
        wordList.add("Tissue paper" to "مناديل ورقية")
        wordList.add("Toilet paper" to "ورق تواليت")
        wordList.add("Toothpaste" to "معجون أسنان")
        wordList.add("Toothbrush" to "فرشاة الأسنان")
        wordList.add("Writing paper" to "ورق كتابة")
        wordList.add("Garbage bag" to "كيس قمامة")
        wordList.add("Bleach" to "تبييض الملابس")
        wordList.add("Detergent" to "منظفات")
        wordList.add("Disinfectant" to "مطهر")
        wordList.add("Trash bag" to "كيس النفايات")
        wordList.add("Duster" to "منفضة غبار")
        wordList.add("Fabric softener" to "منعم غسيل")
        wordList.add("Floor cloth" to "ممسحة أرض")
        wordList.add("Furniture polish" to "مادة لتلميع الأثاث")
        wordList.add("Vacuum cleaner bag" to "كيس المكنسة الكهربائية")
        wordList.add("Shoe polish" to "مادة لتلميع الأحذية")
        wordList.add("Soap" to "صابون")
        wordList.add("Washing powder" to "مسحوق غسيل")
        wordList.add("By bicycle" to "بالدراجة")
        wordList.add("By boat" to "بالقارب")
        wordList.add("By bus" to "بالباص أو بالحافلة")
        wordList.add("By car" to "بالسيارة")
        wordList.add("By coach" to "بالحافلة")
        wordList.add("By ferry" to "بالعبّارة")
        wordList.add("By motorcycle" to "بالدراجة النارية")
        wordList.add("By plane" to "بالطائرة")
        wordList.add("By train" to "بالقطار")
        wordList.add("On foot" to "مشيا على الأقدام")
        wordList.add("Box office" to "شباك تذاكر")
        wordList.add("Travel agent" to "وكيل سفر")
        wordList.add("Brochure" to "كتيب – نشرة")
        wordList.add("Price" to "سعر أو ثمن")
        wordList.add("Fare" to "أجرة")
        wordList.add("Ticket" to "تذكرة")
        wordList.add("Booking" to "حجز")
        wordList.add("Reservation" to "حجز")
        wordList.add("Passenger" to "راكب")
        wordList.add("Destination" to "وجهة")
        wordList.add("Itinerary" to "خط سير الرحلة")
        wordList.add("Journey" to "رحلة")
        wordList.add("Travel insurance" to "تأمين للسفر")
        wordList.add("Holiday" to "عطلة")
        wordList.add("Sightseeing" to "مشاهدة معالم المدينة")
        wordList.add("Business trip" to "رحلة عمل")
        wordList.add("To book" to "أن يحجز")
        wordList.add("To cancel a booking" to "لإلغاء الحجز")
        wordList.add("Arrive" to "يصل")
        wordList.add("Leave" to "يغادر")
        wordList.add("Depart" to "يغادر")
        wordList.add("Travel" to "يسافر")
        wordList.add("Visit" to "يزور")
        wordList.add("Cancellation" to "إلغاء")
        wordList.add("Customs" to "جمارك")
        wordList.add("Delay" to "تأخير")
        wordList.add("Luggage" to "الامتعة")
        wordList.add("Map" to "خارطة")
        wordList.add("Passport control" to "مراقبة الجوازات")
        wordList.add("Suitcase" to "حقيبة سفر")
        wordList.add("Cancelled" to "ألغى")
        wordList.add("Delayed" to "متأخر")
        wordList.add("Bypass" to "طريق جانبي")
        wordList.add("Lane" to "حارة – ممر")
        wordList.add("Dual carriage way" to "طريق مزدوج للسيارات")
        wordList.add("Main road" to "طريق رئيسي")
        wordList.add("Motorway" to "طريق سريعة")
        wordList.add("One-way-street" to "شارع باتجاه واحد")
        wordList.add("Ringroad" to "طريق دائري")
        wordList.add("Road" to "طريق أو شارع")
        wordList.add("Tollroad" to "طريق برسم مرور")
        wordList.add("Corner" to "زاوية, ركن")
        wordList.add("Crossroads" to "تقاطع طرق")
        wordList.add("Kerb" to "رصيف")
        wordList.add("Fork, crossway" to "مفترق طرق")
        wordList.add("Junction" to "تقاطع")
        wordList.add("Parking spaces" to "مكان وقوف السيارات")
        wordList.add("Level crossing" to "تقاطع – معابر السكة الحديدية")
        wordList.add("Pavement" to "رصيف الشارع")
        wordList.add("Crosswalk" to "ممر مشاة")
        wordList.add("Road sign" to "لافتة طريق")
        wordList.add("Roadside" to "طرف - جانب الطريق")
        wordList.add("Roadworks" to "أعمال صيانة الطرق")
        wordList.add("Roundabout" to "دوّار")
        wordList.add("Services" to "خدمات – مرافق")
        wordList.add("Signpost" to "لافتة")
        wordList.add("Speedlimit" to "الحد الأقصى للسرعة")
        wordList.add("T-Junction" to "تقاطع طرق على شكل حرف T")
        wordList.add("Toll" to "ضريبة طرق")
        wordList.add("Trafficlight" to "إشارة مرور")
        wordList.add("Turning" to "دوران – منعطف")
        wordList.add("Accident" to "حادث")
        wordList.add("Breakdown" to "تعطل– انهيار")
        wordList.add("Breathalyser" to "جهاز قياس مستوى الكحول للسائق")
        wordList.add("Jack" to "رافعة سيارات")
        wordList.add("Jump leads" to "أسلاك أو وصلة بطارية السيارة")
        wordList.add("Flat tire" to "إطار فارغ – عجلة مثقوبة")
        wordList.add("Fog" to "ضباب")
        wordList.add("Icy road" to "طريق جليدي")
        wordList.add("Puncture" to "ثقب أو خرم في العجلة")
        wordList.add("Speeding fine" to "غرامة تجاوز السرعة")
        wordList.add("Spray" to "رشاش")
        wordList.add("Traffic jam" to "ازدحام مروري")
        wordList.add("Crash" to "تحّطّم – اصطدام")
        wordList.add("Disaster" to "كارثة")
        wordList.add("Slide" to "ينزلق")
        wordList.add("Engine stop" to "توقف المحرك")
        wordList.add("Swerve" to "انحراف")
        wordList.add("Driving instructor" to "معلم سياقة")
        wordList.add("Driving lesson" to "درس سياقة")
        wordList.add("Driving licence" to "شهادة أو رخصة قيادة")
        wordList.add("Driving school" to "مدرسة لتعليم القيادة")
        wordList.add("Driving test" to "امتحان سياقة")
        wordList.add("Learner driver" to "سائق قيد التمرين")
        wordList.add("Failed to driving test" to "فشل في اختبار القيادة")
        wordList.add("Passed the driving test" to "اجتاز اختبار القيادة")
        wordList.add("Car park" to "موقف سيارات")
        wordList.add("Parking for disabled" to "موقف سيارات للمعاقين")
        wordList.add("Multi storey car park" to "موقف سيارات متعدد الطوابق")
        wordList.add("To stop the car" to "لإيقاف السيارة")
        wordList.add("Parking meter" to "عداد مواقف السيارات")
        wordList.add("Parking space" to "مساحة لوقوف السيارات")
        wordList.add("Parking ticket" to "تذكرة وقوف السيارات")
        wordList.add("Traffic warden" to "مأمور مرور")
        wordList.add("Car wash" to "مغسلة سيارات")
        wordList.add("Diesel" to "ديزل")
        wordList.add("Oil" to "نفط")
        wordList.add("Petrol" to "بنزين")
        wordList.add("Fuel pump" to "مضخة وقود")
        wordList.add("Petrol station" to "محطة وقود")
        wordList.add("Unleaded fuel" to "وقود خالي من الرصاص")
        wordList.add("Bike - Bicycle" to "دراجة")
        wordList.add("Van" to "فان عربة – شاحنة")
        wordList.add("Bus" to "حافلة أو باص")
        wordList.add("Car" to "سيارة")
        wordList.add("Caravan" to "بيت نقّاّل - مقطورة")
        wordList.add("Coach" to "حافلة – مدرّب")
        wordList.add("Lorry" to "شاحنة")
        wordList.add("Mini bus" to "حافلة صغيرة")
        wordList.add("Moped" to "دراجة هوائية")
        wordList.add("Motor cycle" to "دراجة نارية")
        wordList.add("Scooter" to "سكوتر")
        wordList.add("Taxi" to "تاكسي - سيارة أجرة")
        wordList.add("Tractor" to "جرّار")
        wordList.add("Truck" to "شاحنة")
        wordList.add("Locomotive" to "قاطرة")
        wordList.add("Car rental company" to "شركة لتأجير السيارات")
        wordList.add("Car Keys" to "مفاتيح السيارة")
        wordList.add("Cyclist" to "راكب الدراجة الهوائية")
        wordList.add("Driver" to "سائق")
        wordList.add("Mechanic" to "ميكانيكي")
        wordList.add("Insurance" to "تأمين")
        wordList.add("Passenger" to "راكب – مسافر")
        wordList.add("Pedestrian" to "مشاة")
        wordList.add("Reverse gear" to "الترس العكسي – تروس الرجوع")
        wordList.add("Road map" to "خارطة الطريق")
        wordList.add("Second hand" to "مستعمل")

        wordList.add("Speed" to "سرعة")
        wordList.add("Crowding" to "ازدحام")
        wordList.add("Tire pressure" to "ضغط الهواء في الإطارات")
        wordList.add("Vehicle" to "عربة - وسيلة نقل")
        wordList.add("Increasing speed" to "زيادة السرعة")
        wordList.add("Braking" to "مكابح – فرامل")
        wordList.add("Change the gears" to "يغير التروس")
        wordList.add("Drive" to "يسوق– يقود")
        wordList.add("Overtake" to "يتجاوز")
        wordList.add("Reverse" to "عكس الاتجاه")
        wordList.add("Slow down" to "يبطيء")
        wordList.add("Speed up" to "يسرع")
        wordList.add("Steer" to "توجيه, قيادة")
        wordList.add("Timetable" to "جدول المواعيد")
        wordList.add("Single ticket" to "تذكرة ذهاب فقط")
        wordList.add("Roundtrip ticket" to "تذكرة ذهاب وإياب")
        wordList.add("Platform" to "رصيف المحطة")
        wordList.add("Waiting room" to "غرفة الانتظار")
        wordList.add("Ticket office" to "مكتب التذاكر - مكتب الحجز")
        wordList.add("Seat" to "مقعد")
        wordList.add("Seat number" to "رقم المقعد")
        wordList.add("Luggage rack" to "رف الأمتعة")
        wordList.add("First class" to "درجة أولى")
        wordList.add("Second class" to "درجة ثانية")
        wordList.add("Ticket inspector" to "مفتش تذاكر")
        wordList.add("Ticket collector" to "جامع التذاكر")
        wordList.add("Penalty fare" to "غرامة")
        wordList.add("Buffet car" to "عربة البوفيه")
        wordList.add("Carriage" to "عربة")
        wordList.add("Compartment" to "مقصورة")
        wordList.add("Derailment" to "خروج القطار عن الخط")
        wordList.add("Express train" to "قطار سريع")
        wordList.add("Guard" to "حارس")
        wordList.add("Train tracks" to "سكة القطار")
        wordList.add("Line closure" to "اغلاق الخط")
        wordList.add("Rail" to "حاجز, سياج")
        wordList.add("Rail card" to "بطاقة قطارات")
        wordList.add("Railway lines" to "خطوط السكك الحديدية")
        wordList.add("Restaurant car" to "عربة المطعم")
        wordList.add("Season ticket" to "تذكرة موسمية")
        wordList.add("Signal" to "إشارة")
        wordList.add("On a train" to "على متن القطار")
        wordList.add("Station" to "محطة")
        wordList.add("Railway station" to "محطة السكك الحديدية")
        wordList.add("Train station" to "محطة القطار")
        wordList.add("Service station" to "محطة توقف")
        wordList.add("Ticket barrier" to "حاجز تذاكر")
        wordList.add("Track" to "سكة – مسار")
        wordList.add("Train" to "قطار")
        wordList.add("Train crash" to "حادث قطار")
        wordList.add("Train driver" to "سائق القطار")
        wordList.add("Train fare" to "أجرة القطار")
        wordList.add("Train journey" to "رحلة القطار")
        wordList.add("Travel card" to "بطاقة السفر")
        wordList.add("Subway station" to "محطة مترو الأنفاق")
        wordList.add("Tunnel" to "نفق")
        wordList.add("To catch the train" to "يلحق بالقطار")
        wordList.add("Get on the train" to "يركب القطار")
        wordList.add("Get off the train" to "ينزل من القطار")
        wordList.add("To miss the flight" to "يفوته الرحلة")
        wordList.add("Bus driver" to "سائق الباص")
        wordList.add("Bus fare" to "أجرة الباص")
        wordList.add("Bus journey" to "رحلة الباص")
        wordList.add("Bus stop" to "موقف الباص")
        wordList.add("Bus lane" to "ممر الحافلة")
        wordList.add("Bus station" to "محطة باصات")
        wordList.add("Coach" to "حافلة كبيرة")
        wordList.add("Coach station" to "محطة الحافلات")
        wordList.add("Double decker bus" to "الحافلة ذات الطابقين")
        wordList.add("Conductor" to "قاطع التذاكر, كمسري")
        wordList.add("Inspector" to "مفتش")
        wordList.add("Luggage trolley" to "عربة الأمتعة")
        wordList.add("Next stop" to "المحطة التالية")
        wordList.add("Hand luggage" to "أمتعة محمولة باليد")
        wordList.add("Stop request" to "طلب التوقف")
        wordList.add("The starting point" to "نقطة الانطلاق")
        wordList.add("Terminus" to "نقطة وصول")
        wordList.add("Riding the bus" to "يركب الحافلة")
        wordList.add("Get out the bus" to "ينزل من الحافلة")
        wordList.add("Catch up with the bus" to "للحاق بالباص")
        wordList.add("To miss a bus" to "أن تفوت الباص")
        wordList.add("Airline" to "خطوط جوية")
        wordList.add("Airport" to "مطار")
        wordList.add("Permissible luggage" to "الأمتعة المسموح بها")
        wordList.add("Consecutive voyages" to "رحلات متعاقبة أو متتالية")
        wordList.add("Flight" to "رحلة جوية")
        wordList.add("Flight Number" to "رقم الرحلة")
        wordList.add("Aircraft" to "الطائرة– طائرات")
        wordList.add("Helicopter" to "طائرة مروحية")
        wordList.add("Jet" to "طائرة نفاثة")
        wordList.add("Plane" to "طائرة")
        wordList.add("To travel by plane" to "ليسافر بالطائرة")
        wordList.add("The plane lands" to "الطائرة تهبط")
        wordList.add("To miss the flight" to "تفوته الرحلة")
        wordList.add("The plane takes off" to "الطائرة تقلع")
        wordList.add("Landing" to "هبوط")
        wordList.add("Take off" to "اقلاع")
        wordList.add("Arrivals" to "القادمون")
        wordList.add("Baggage reclaim" to "استعادة الامتعة")
        wordList.add("Baggage handing" to "تسليم الامتعة")
        wordList.add("Boarding" to "الصعود الى الطائرة")
        wordList.add("Boarding card" to "بطاقة الصعود للطائرة")
        wordList.add("Seatbelt" to "حزام المقعد")
        wordList.add("Check in desk" to "مكتب تسجيل الوصول")
        wordList.add("Departure lounge" to "صالة المغادرة")
        wordList.add("Departures" to "مغادرون")
        wordList.add("Unauthorized baggage" to "الأمتعة غير المصرح بها")
        wordList.add("Hold luggage" to "عقد الامتعة")
        wordList.add("Passport" to "جواز سفر")
        wordList.add("Runway" to "مدرج المطار")
        wordList.add("Security" to "أمن")
        wordList.add("Trolley" to "عربة")
        wordList.add("Pilot" to "طيار")
        wordList.add("Captain" to "القبطان")
        wordList.add("Copilot" to "مساعد طيار")
        wordList.add("Flight attendant" to "مضيف طيران")
        wordList.add("Air stewardess" to "مضيفة جوية")
        wordList.add("Aisle seat" to "مقعد بجوار الممر")
        wordList.add("In flight entertainment" to "الترفيه على متن الطائرة")
        wordList.add("Meal on board" to "وجبة على متن الطائرة")
        wordList.add("Buckle up" to "ربط حزام أمان")
        wordList.add("Turbulence" to "إضطراب جوي")
        wordList.add("Window seat" to "مقعد بجوار النافذة")
        wordList.add("Aisle" to "الممر")
        wordList.add("Cabin" to "المقصورة")
        wordList.add("Cockpit" to "قمرة القيادة")
        wordList.add("Engine" to "محرك")
        wordList.add("Landing gear" to "معدات الهبوط")
        wordList.add("Propeller" to "المروحة")
        wordList.add("Wing" to "الجناح")
        wordList.add("North" to "الشمال")
        wordList.add("Northeast" to "الشمال الشرقي")
        wordList.add("East" to "الشرق")
        wordList.add("Southeast" to "الجنوب الشرقي")
        wordList.add("South" to "الجنوب")
        wordList.add("Southwest" to "الجنوب الغربي")
        wordList.add("West" to "الغرب")
        wordList.add("Northwest" to "الشمال الغربي")
        wordList.add("Compass" to "البوصلة")
        wordList.add("Compass reading" to "قراءة البوصلة")
        wordList.add("Check in" to "تسجيل الدخول")
        wordList.add("Logged out" to "مغادرة) تسجيل الخروج (")
        wordList.add("Reservation" to "حجز")
        wordList.add("Vacancy" to "شاغر")
        wordList.add("To book" to "للحجز")
        wordList.add("Login" to "تسجيل الدخول")
        wordList.add("Logout" to "يغادر أو يسلم الغرفة")
        wordList.add("Pay the bill" to "يدفع الفاتورة")
        wordList.add("Staying at the hotel" to "يقيم في الفندق")
        wordList.add("Hotel" to "فندق")
        wordList.add("Hotel with breakfast service" to "فندق مع خدمة الإفطار")
        wordList.add("Guest house" to "دار الضيافة")
        wordList.add("Hostel" to "نزل")
        wordList.add("Campsite" to "المخيم")
        wordList.add("Single room" to "غرفة فردية")
        wordList.add("Double room" to "غرفة مزدوجة")
        wordList.add("Twin room" to "غرفة ثنائية")
        wordList.add("Triple room" to "غرفة ثلاثية")
        wordList.add("Suite" to "جناح")
        wordList.add("Air conditioning" to "مكيف")
        wordList.add("Bath" to "مغطس")
        wordList.add("Suite bathroom" to "حمام داخلي")
        wordList.add("Internet" to "انترنت")
        wordList.add("Minibar" to "بار صغير")
        wordList.add("Safe" to "خزنة")
        wordList.add("Shower" to "دش")
        wordList.add("Bar" to "حانة")
        wordList.add("Corridor" to "دهليز")
        wordList.add("Fire escape" to "مخرج حريق للطواريء")
        wordList.add("Game room" to "غرفة الألعاب")
        wordList.add("Gym" to "صالة رياضية")
        wordList.add("Laundry service" to "خدمة غسيل الملابس")
        wordList.add("Lift" to "مصعد")
        wordList.add("Hotel lobby" to "ردهة الفندق")
        wordList.add("Reception desk" to "مكتب إستقبال")
        wordList.add("Restaurant" to "مطعم")
        wordList.add("Room service" to "خدمة الغرف")
        wordList.add("Sauna" to "حمام بخار ) ساونا (")
        wordList.add("Swimming pool" to "حمام السباحة")
        wordList.add("Manager" to "مدير")
        wordList.add("Housekeeper" to "مدبرة المنزل")
        wordList.add("Receptionist" to "موظف الاستقبال")
        wordList.add("Servant" to "خادم")
        wordList.add("Housemaid" to "خادمة")
        wordList.add("Doorman" to "بوّاب")
        wordList.add("Porter" to "حمّال")
        wordList.add("Fire alarm" to "جرس إنذار حريق")
        wordList.add("Laundry" to "غسيل الثياب")
        wordList.add("Room key" to "مفتاح الغرفة")
        wordList.add("Room number" to "رقم الغرفة")
        wordList.add("Wake up call" to "إتصال إيقاظ")
        wordList.add("Fresh" to "طازج")
        wordList.add("Mouldy" to "متعفن")
        wordList.add("Expired" to "منتهي الصلاحية")
        wordList.add("Rotten" to "فاسد")
        wordList.add("Stale bread" to "خبز قديم أو ناشف")
        wordList.add("Juicy" to "مليئ بالعصارة")
        wordList.add("Ripe" to "ناضجة")
        wordList.add("Unripe" to "غير ناضجة")
        wordList.add("Tender" to "ليّن")
        wordList.add("Tough" to "قاس صلب")
        wordList.add("Over cooked" to "مفرط في طهيه")
        wordList.add("Uncooked" to "غير مطبوخ – نيء")
        wordList.add("Bland" to "لطيف")
        wordList.add("Delicious" to "لذيذ")
        wordList.add("Horrible" to "فظيع")
        wordList.add("Poor" to "ضعيف المستوى")
        wordList.add("Salty" to "مالح")
        wordList.add("Sickly" to "غير صحي")
        wordList.add("Sweet" to "حلو")
        wordList.add("Sour" to "حامض")
        wordList.add("Tasty" to "لذيذ")
        wordList.add("Spicy" to "حار")
        wordList.add("Mild" to "خفيفة – معتدل")
        wordList.add("To bake" to "يخبز")
        wordList.add("To boil" to "يغلي")
        wordList.add("To fry" to "يقلي")
        wordList.add("To grill" to "يشوي")
        wordList.add("To roast" to "يحمص")
        wordList.add("To steam" to "يطبخ على البخار")
        wordList.add("Breakfast" to "الإفطار")
        wordList.add("Lunch" to "الغداء")
        wordList.add("Tea" to "شاي")
        wordList.add("Dinner" to "العشاء")
        wordList.add("Supper" to "طعام العشاء")

        wordList.add("Have breakfast" to "تناول الإفطار")
        wordList.add("Have lunch" to "تناول الغداء")
        wordList.add("Have dinner" to "تناول العشاء")
        wordList.add("Ingredient" to "عنصر")
        wordList.add("Recipe" to "وصفة")
        wordList.add("To cook" to "يطهو")
        wordList.add("To set the table" to "يجهز طاولة الطعام")
        wordList.add("To clear the table" to "ينظف الطاولة")
        wordList.add("To come to the table" to "يأتي إلى الطاولة")
        wordList.add("To leave the table" to "يغادر الطاولة")
        wordList.add("To wipe the table" to "يمسح الطاولة")
        wordList.add("To prepare a meal" to "يعد وجبة")
        wordList.add("Bacon" to "لحم خنزير مقدد")
        wordList.add("Beef" to "لحم بقر")
        wordList.add("Chicken" to "دجاج")
        wordList.add("Cooked meat" to "لحم مطبوخ")
        wordList.add("Duck" to "بط")
        wordList.add("Ham" to "لحم فخذ الخنزير")
        wordList.add("Kidneys" to "كُلى - كليتين")
        wordList.add("Lamb meat" to "لحم حمَل")
        wordList.add("Liver" to "كبد")
        wordList.add("Minced beef" to "لحم بقر مفروم")
        wordList.add("Grilled chicken" to "دجاج مشوي")
        wordList.add("Salami" to "السجق– شرائح لحم")
        wordList.add("Sausage" to "نقانق")
        wordList.add("Pork" to "لحم خنزير")
        wordList.add("Pork pie" to "فطيرة لحم خنزير")
        wordList.add("Rolls sausage" to "لفائف النقانق")
        wordList.add("Turkey" to "ديك رومي")
        wordList.add("Veal" to "لحم العجل")
        wordList.add("Apple" to "تفاح")
        wordList.add("Apricot" to "مشمش")
        wordList.add("Banana" to "موز")
        wordList.add("Black berry" to "توت أسود")
        wordList.add("Black currant" to "كشمش أسود")
        wordList.add("Blue berry" to "توت أزرق")
        wordList.add("Cherry" to "كرز")
        wordList.add("Coconut" to "جوز الهند")
        wordList.add("Fig" to "تين")
        wordList.add("Goose berry" to "عنب الثعلب")
        wordList.add("Grape" to "عنب")
        wordList.add("Grape fruit" to "جريب فروت")
        wordList.add("Kiwi fruit" to "فاكهة الكيوي")
        wordList.add("Lemon" to "ليمون")
        wordList.add("Lime" to "ليمون حامض")
        wordList.add("Mango" to "مانغو")
        wordList.add("Melon" to "شمام")
        wordList.add("Orange" to "برتقال")
        wordList.add("Peach" to "خوخ")
        wordList.add("Pear" to "إجاص - كمثرى")
        wordList.add("Pineapple" to "أناناس")
        wordList.add("Plum" to "خوخ – برقوق")
        wordList.add("Pomegranate" to "رمان")
        wordList.add("Raspberry" to "توت شوكي")
        wordList.add("Redcurrant" to "كشمش أحمر")
        wordList.add("Rhubarb" to "راوند")
        wordList.add("Strawberry" to "فراولة")
        wordList.add("A bunch of bananas" to "حفنة من الموز")
        wordList.add("A bunch of grapes" to "حفنة من العنب")
        wordList.add("Anchovy fish" to "سمكة الأنشوفة")
        wordList.add("Cod" to "سمكة قد")
        wordList.add("Haddock" to "سمكة حدوق")
        wordList.add("Herring" to "سمكة الرنجة")
        wordList.add("Kipper" to "سمك مدخن")
        wordList.add("Mackerel fish" to "سمكة قمري")
        wordList.add("Pilchard" to "سمك بلشار")
        wordList.add("Plaice" to "سمكة بلايس")
        wordList.add("Salmon" to "سمكة سلمون")
        wordList.add("Sardine" to "سمكة سردين")
        wordList.add("Smoked Salmon" to "سمكة سلمون مدخن")
        wordList.add("Sole" to "سمك موسى")
        wordList.add("Trout" to "سمكة تروت")
        wordList.add("Tuna" to "سمكة تونا")
        wordList.add("Artichoke" to "خرشوف - أرضي شوكي")
        wordList.add("Asparagus" to "الهليون")
        wordList.add("Aubergine" to "باذنجان")
        wordList.add("Avocado" to "أفوكادو")
        wordList.add("Beansprouts" to "فاصوليا مبرعمة")
        wordList.add("Beetroot" to "الشمندر")
        wordList.add("Broad bean" to "فول")
        wordList.add("Broccoli" to "بروكلي")
        wordList.add("Brussels sprout" to "كرنب مسلوق")
        wordList.add("Cabbage" to "كرنب (ملفوف)")
        wordList.add("Carrot" to "جزر")
        wordList.add("Cauliflower" to "قرنبيط")
        wordList.add("Celery" to "كرفس")
        wordList.add("Pepper chili" to "الفلفل الحار")
        wordList.add("Courgette" to "الكوسا")
        wordList.add("Cucumber" to "خيار")
        wordList.add("French beans" to "فاصوليا فرنسية")
        wordList.add("Garlic" to "ثوم")
        wordList.add("Ginger" to "الزنجبيل")
        wordList.add("Leek" to "كرّاث")
        wordList.add("Lettuce" to "خس")
        wordList.add("Mushroom" to "فطر")
        wordList.add("Onion" to "بصل")
        wordList.add("Peas" to "بازلاء")
        wordList.add("Pepper" to "فلفل")
        wordList.add("Potato" to "بطاطا")
        wordList.add("Pumpkin" to "يقطين – قرع")
        wordList.add("Radish" to "الفجل")
        wordList.add("Arugula" to "جرجير")
        wordList.add("Bean" to "فاصولياء")
        wordList.add("Yellow turnip" to "اللفت الأصفر")
        wordList.add("Sweet potato" to "بطاطا حلوة")
        wordList.add("Corn" to "ذرة")
        wordList.add("Tomato" to "طماطم")
        wordList.add("Turnip" to "لفت")
        wordList.add("Spinach" to "السبانخ")
        wordList.add("Spring onion" to "بصل أخضر")
        wordList.add("Pumpkins" to "القرع - اليقطين")
        wordList.add("Clove of garlic" to "فص من الثوم")
        wordList.add("Celery stick" to "عصا من الكرفس")
        wordList.add("Cooked beans" to "فول مطبوخ")
        wordList.add("Corned beef" to "لحم بقر معلب")
        wordList.add("Kidney bean" to "الفاصوليا - لوبيا")
        wordList.add("Soup" to "الحساء أو الشوربة")
        wordList.add("Canned tomatoes" to "طماطم معلبة")
        wordList.add("Chips" to "رقائق بطاطس مقلية")
        wordList.add("Fish fingers" to "أصابع سمك")
        wordList.add("Frozen peas" to "بازلاء مجمدة")
        wordList.add("Frozen pizza" to "البيتزا المجمدة")
        wordList.add("Ice cream" to "مثلجات")
        wordList.add("Cooking oil" to "زيت الطبخ")
        wordList.add("Olive oil" to "زيت الزيتون")
        wordList.add("Stock cubes" to "مكعبات مرقة")
        wordList.add("Tomato puree" to "معجون الطماطم")
        wordList.add("Butter" to "زبدة")
        wordList.add("Cream" to "قشطة")
        wordList.add("Cheese" to "جبن")
        wordList.add("Blue cheese" to "الجبن الأزرق")
        wordList.add("Cottage cheese" to "الجبن الأبيض")
        wordList.add("Goat cheese" to "جبن الماعز")
        wordList.add("Fresh cream" to "قشطة طازجة")
        wordList.add("Eggs" to "بيض")
        wordList.add("Poached eggs" to "بيض مسلوق")
        wordList.add("Margarine" to "سمن نباتي")
        wordList.add("Milk" to "حليب")
        wordList.add("Full fat milk" to "حليب كامل الدسم")
        wordList.add("Semi skimmed milk" to "حليب نصف الدسم")
        wordList.add("Skimmed milk" to "حليب خالي الدسم")
        wordList.add("Sour cream" to "قشطة حامضة")
        wordList.add("Yoghurt" to "لبن - زبادي")
        wordList.add("Baguette" to "باغيت (رغيف فرنسي)")
        wordList.add("Barley bread" to "خبز الشعير")
        wordList.add("Brown bread" to "خبز أسمر")
        wordList.add("White bread" to "خبز أبيض")
        wordList.add("Garlic bread" to "خبز بالثوم")
        wordList.add("Cornbread" to "خبز الذرة")
        wordList.add("Loaf" to "رغيف")
        wordList.add("Sliced loaf" to "رغيف مقطع إلى شرائح")
        wordList.add("Cake" to "كعكة")
        wordList.add("Danish pastries" to "المعجنات الدنماركية")
        wordList.add("Quiche" to "حلوى الكوينش")
        wordList.add("Sponge cake" to "كعكة إسفنجية")
        wordList.add("Baking powder" to "مسحوق الخبز")
        wordList.add("Flour" to "طحين")
        wordList.add("Chickpea flour" to "دقيق الحمص")
        wordList.add("Cornflour" to "دقيق الذرة")
        wordList.add("Sugar" to "سكر")
        wordList.add("Brown sugar" to "سكر بني")
        wordList.add("Icing sugar" to "مسحوق السكر")
        wordList.add("Pastry" to "المعجنات")
        wordList.add("Yeast" to "الخميرة")
        wordList.add("Dried apricots" to "المشمش المجفف")
        wordList.add("Prunes" to "الخوخ")
        wordList.add("Dates" to "تمر")
        wordList.add("Raisins" to "الزبيب")
        wordList.add("Sultanas" to "الكشمش عنب لا بزر له")
        wordList.add("Breakfast cereal" to "حبوب الفطور")
        wordList.add("Cornflakes" to "رقائق الذرة")
        wordList.add("Honey" to "العسل")
        wordList.add("Jam" to "مربى")
        wordList.add("Strawberry jam" to "مربى الفراولة")
        wordList.add("Porridge" to "عصيدة")
        wordList.add("Toast" to "خبز محمص")
        wordList.add("Noodles" to "معكرونة")
        wordList.add("Pasta" to "باستا (معكرونة)")
        wordList.add("Pasta sauce" to "صلصة الباستا")
        wordList.add("Pizza" to "بيتزا")
        wordList.add("Rice" to "أرز")
        wordList.add("Spaghetti" to "معكرونة")
        wordList.add("Ketchup" to "كاتشب (صلصة الطماطم)")
        wordList.add("Mayonnaise" to "مايونيز")
        wordList.add("Mustard" to "خردل")
        wordList.add("Salad dressing" to "توابل السلطة")
        wordList.add("Salt" to "ملح")
        wordList.add("Vinaigrette sauce" to "صلصة الخل")
        wordList.add("Vinegar" to "خل")
        wordList.add("Biscuits" to "بسكويت")
        wordList.add("Chocolate" to "شوكولاته")
        wordList.add("Crisps" to "رقائق البطاطس المقلية")
        wordList.add("Chickpeas" to "حمص")
        wordList.add("Nuts" to "مكسرات")
        wordList.add("Olives" to "زيتون")
        wordList.add("Peanuts" to "الفول السوداني")
        wordList.add("Sweets" to "حلويات")
        wordList.add("Walnuts" to "الجوز")
        wordList.add("Basil" to "حبق أو ريحان")
        wordList.add("Chives" to "ثوم معمر")
        wordList.add("Coriander" to "كزبرة")
        wordList.add("Dill" to "شبت")
        wordList.add("Parsley" to "بقدونس")
        wordList.add("Rosemary" to "حصى البان – أكليل الجبل")
        wordList.add("Sage" to "مريمية")
        wordList.add("Thyme" to "زعتر")
        wordList.add("Chilli powder" to "مسحوق الفلفل الحار")
        wordList.add("Cinnamon" to "القرفة")
        wordList.add("Cumin" to "كمون")
        wordList.add("Curry powder" to "مسحوق الكاري")
        wordList.add("Nutmeg" to "جوزة الطيب")
        wordList.add("Paprika" to "الفلفل الحلو")
        wordList.add("Saffron" to "الزعفران")
        wordList.add("Organic product" to "منتج عضويّ")
        wordList.add("Fast food" to "الوجبات السريعة")
        wordList.add("Bag of potatoes" to "كيس من البطاطا")
        wordList.add("Mold of chocolate" to "قالب الشوكولاته")
        wordList.add("Bottle of milk" to "زجاجة حليب")
        wordList.add("Carton of milk" to "علبة حليب")
        wordList.add("Box of eggs" to "علبة البيض")
        wordList.add("Jar of jam" to "علبة المربى")
        wordList.add("Pack of butter" to "قالب من الزبدة")
        wordList.add("Packet of biscuits" to "علبة من بسكويت")
        wordList.add("Bag of chips" to "كيس من رقائق البطاطس")
        wordList.add("Box of cheese" to "علبة من الجبن")
        wordList.add("A pot of strawberries" to "وعاء من الفراولة")
        wordList.add("Baked beans" to "فاصولياء مطبوخة")
        wordList.add("Bowl of ice cream" to "وعاء من الايس كريم")
        wordList.add("Coke / Cola" to "كولا – مشروب غازي")
        wordList.add("Fruit juice" to "عصير فواكه")
        wordList.add("Grapefruit juice" to "عصير جريب فروت")
        wordList.add("Orange juice" to "عصير البرتقال")
        wordList.add("Pineapple juice" to "عصير الأناناس")
        wordList.add("Tomato juice" to "عصير الطماطم")
        wordList.add("Iced tea" to "شاي مثلج")
        wordList.add("Lemonade" to "عصير الليمون")
        wordList.add("Linden juice" to "عصير الزيزفون")
        wordList.add("Milk shake" to "مخفوق الحليب")
        wordList.add("Orange squash" to "فوار البرتقال")
        wordList.add("Fizz" to "شراب فوار")
        wordList.add("Smoothie" to "عصير")
        wordList.add("Drink" to "شراب")
        wordList.add("Water" to "ماء")
        wordList.add("Mineral water" to "مياه معدنية")
        wordList.add("Stagnant water" to "مياه راكدة")
        wordList.add("Sparkling water" to "ماء فوار")
        wordList.add("Tap water" to "ماء حنفية")
        wordList.add("Cocoa" to "شراب الكاكاو")
        wordList.add("Coffee" to "قهوة")

        wordList.add(""   to "" )
        wordList.add(""   to "" )
        wordList.add(""   to "" )
        wordList.add(""   to "" )
        wordList.add(""   to "" )
        wordList.add(""   to "" )
        wordList.add(""   to "" )
        wordList.add(""   to "" )
        wordList.add(""   to "" )
        wordList.add(""   to "" )
        wordList.add(""   to "" )
        wordList.add(""   to "" )
        wordList.add(""   to "" )
        wordList.add(""   to "" )
        wordList.add(""   to "" )
        wordList.add(""   to "" )
        wordList.add(""   to "" )
        wordList.add(""   to "" )
        wordList.add(""   to "" )
        wordList.add(""   to "" )
        wordList.add(""   to "" )
        wordList.add(""   to "" )
        wordList.add(""   to "" )
        wordList.add(""   to "" )
        wordList.add(""   to "" )

    }
}
