package com.sarrawi.tts
//
//import android.os.Bundle
//import android.speech.tts.TextToSpeech
//import androidx.appcompat.app.AppCompatActivity
//import androidx.recyclerview.widget.DiffUtil
//import androidx.recyclerview.widget.LinearLayoutManager
//import androidx.recyclerview.widget.RecyclerView
//import java.util.Locale
//
//class MainActivity2 : AppCompatActivity(), TextToSpeech.OnInitListener {
//
//    private lateinit var tts: TextToSpeech
//    private lateinit var recyclerView: RecyclerView
//    private lateinit var adapter: WordAdapter
//    private var wordList = mutableListOf<Pair<String, String>>()
//    private var oldList = wordList.toList() // لحفظ القائمة القديمة
//
//    override fun onCreate(savedInstanceState: Bundle?) {
//        super.onCreate(savedInstanceState)
//        setContentView(R.layout.activity_main2)
//
//        recyclerView = findViewById(R.id.recyclerView)
//        tts = TextToSpeech(this, this)
//
//        recyclerView.layoutManager = LinearLayoutManager(this)
//        adapter = WordAdapter(this, wordList, tts)
//        recyclerView.adapter = adapter
//
//        // تحميل البيانات
//        loadData()
//    }
//
//    private fun loadData() {
//        val newList = mutableListOf<Pair<String, String>>()
//        newList.add("Word " to "معنى ")
//
//        val wordList = listOf(
//            "Hello" to "مرحبا",
//            "Goodbye" to "وداعا",
//            "Thank you" to "شكرا"
//            // أضف المزيد من الكلمات والمعاني هنا
//        )
//        // استخدام DiffUtil لتحديث RecyclerView
//        val diffCallback = WordDiffCallback(oldList, newList)
//        val diffResult = DiffUtil.calculateDiff(diffCallback)
//
//        wordList = newList
//        diffResult.dispatchUpdatesTo(adapter)
//        oldList = newList // تحديث القائمة القديمة
//    }
//
//    override fun onInit(status: Int) {
//        if (status == TextToSpeech.SUCCESS) {
//            tts.language = Locale.US
//        }
//    }
//
//    override fun onDestroy() {
//        if (::tts.isInitialized) {
//            tts.stop()
//            tts.shutdown()
//        }
//        super.onDestroy()
//    }
//}
//



import android.os.Bundle
import android.speech.tts.TextToSpeech
import androidx.appcompat.app.AppCompatActivity
import androidx.recyclerview.widget.GridLayoutManager
import androidx.recyclerview.widget.RecyclerView
import java.util.Locale
import androidx.recyclerview.widget.LinearLayoutManager


class MainActivity2 : AppCompatActivity(), TextToSpeech.OnInitListener {

    private lateinit var tts: TextToSpeech
    private lateinit var recyclerView: RecyclerView
    val wordList = mutableListOf<Pair<String, String>>()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main2)

        recyclerView = findViewById(R.id.recyclerView)

        tts = TextToSpeech(this, this)

//        val wordList = listOf(
//            "Hello" to "مرحبا",
//            "Goodbye" to "وداعا",
//            "Thank you" to "شكرا"
//            // أضف المزيد من الكلمات والمعاني هنا
//        )

        arrayList()

        // إعداد LinearLayoutManager بدلاً من GridLayoutManager
        val layoutManager = LinearLayoutManager(this)
        recyclerView.layoutManager = layoutManager

        val adapter = WordAdapter(this, wordList, tts)
        recyclerView.adapter = adapter
    }

    override fun onInit(status: Int) {
        if (status == TextToSpeech.SUCCESS) {
            tts.language = Locale.US
        }
    }

    override fun onDestroy() {
        if (::tts.isInitialized) {
            tts.stop()
            tts.shutdown()
        }
        super.onDestroy()
    }

    fun arrayList(){

        wordList.add("Word " to "معنى ")
        wordList.add("Countryside"  to " الريف" )
        wordList.add("Hill"         to " تل" )
        wordList.add("Mountain"     to "جبل" )
        wordList.add("Valley"       to "وادي" )
        wordList.add("Wood"         to "خشب" )
        wordList.add("Forest"       to "غابة" )
        wordList.add("Copse"        to "الشجر الكثير الملتف, الأيكة" )
        wordList.add("Field"        to "حقل" )
        wordList.add("Meadow"       to "مرج" )
        wordList.add("Plain"        to "سهل" )
        wordList.add("Moor"         to "أرض بور" )
        wordList.add("Bog"          to "بركة, مستنقع" )
        wordList.add("Swamp"        to "مستنقع" )
        wordList.add("Hedge"        to "سياج من الشجيرات" )
        wordList.add("Path"         to "مسار, ممر" )
        wordList.add("Fence"        to "سور, سياج" )
        wordList.add("Wall"         to "حائط" )
        wordList.add("Ditch"        to "خندق" )
        wordList.add("Gate"         to "بوابة" )
        wordList.add("Farm"         to "مزرعة" )
        wordList.add("Bridge"       to "جسر، كوبري" )
        wordList.add("Desert"       to "صحراء" )
        wordList.add("Glacier"      to "نهر الجليد" )
        wordList.add("Jungle"       to "دغل  مفرد أدغال " )
        wordList.add("Rainforest"   to "غابة   مطيرة" )
        wordList.add("Volcano"         to "بركان" )
        wordList.add("Stream"          to "تيّارمائي" )
        wordList.add("River"           to "نهر" )
        wordList.add("Canal"           to "قناة" )
        wordList.add("Pond"            to "بركة" )
        wordList.add("Lake"            to "بحيرة" )
        wordList.add("Reservoir"       to "خزان، صهريج" )
        wordList.add("Waterfall"       to " شلال" )
        wordList.add("Well"            to "حسنا" )
        wordList.add("Dam"             to "سد" )
        wordList.add("Power station"   to "محطة كهرباء" )
        wordList.add("Wind farm"       to "مزرعة   الرياح" )
        wordList.add("Mine"            to "منجم" )
        wordList.add("Quarry"          to "مقلع الحجارة" )
        wordList.add("Agriculture"     to "زراعة" )
        wordList.add("Barn"            to "حظيرة" )
        wordList.add("Ranch"           to "مزرعة" )
        wordList.add("Crop"            to "محصول" )
        wordList.add("Harvest"         to "حصاد" )
        wordList.add("Hay"             to "قش – تبن" )
        wordList.add("Wheat"           to "قمح" )
        wordList.add("Irrigation"      to "ري - سقي" )
        wordList.add("Livestock"       to "ماشية" )
        wordList.add("Plough"          to "حرث" )
        wordList.add("Reaping"         to "حصد - جني" )
        wordList.add("Ocean"              to "محيط" )
        wordList.add("Sea"                to "بحر" )
        wordList.add("Shore – Coast"      to "ساحل" )
        wordList.add("Beach"              to "شاطئ" )
        wordList.add("Cliff"              to "جرف - منحدر" )
        wordList.add("Island"             to "جزيرة" )
        wordList.add("Peninsula"          to "شبه الجزيرة" )
        wordList.add("Rock"               to "صخرة" )
        wordList.add("Tide"               to "مد و جزر" )
        wordList.add("Wave"               to "موج" )
        wordList.add("Pier"               to "رصيف بحري" )
        wordList.add("Lighthouse"         to "منارة" )
        wordList.add("Harbour"            to "ميناء" )
        wordList.add("Oil rig"            to "جهاز الحفر النفطي" )
        wordList.add("Country"            to "بلد" )
        wordList.add("City"               to "مدينة" )
        wordList.add("Town"               to "بلدة" )
        wordList.add("Village"            to "قرية" )
        wordList.add("Eruption"           to "ثوران" )
        wordList.add("Earthquake"         to "زلزال" )
        wordList.add("Tsunami"            to "إعصار بحري" )
        wordList.add("Avalanche"          to "انهيار جليدي" )
        wordList.add("Landslide"                to "إنهيار ارضي" )
        wordList.add("Lava"                     to "حمم" )
        wordList.add("Capital  - Capital city"  to "عاصمة" )
        wordList.add("Border"          to "حدود" )
        wordList.add("Nationalpark"    to "حديقة وطنية" )
        wordList.add("Northpole"       to "القطب الشمالي" )
        wordList.add("Southpole"       to "القطب الجنوبي" )
        wordList.add("Equator"         to "خط الاستواء" )
        wordList.add("Longitude"       to "خط الطول" )
        wordList.add("Latitude"        to "خط العرض" )
        wordList.add("Sealevel"        to "مستوى سطح البحر" )
        wordList.add("Erosion"         to "تآكل – تعرية" )
        wordList.add("Pollution"       to "تلوث" )
        wordList.add("Atmosphere"      to "الغلاف الجوي" )
        wordList.add("Environment"     to "بيئة" )
        wordList.add("Population"      to "عدد السكان" )
        wordList.add("Famine"          to "مجاعة" )
        wordList.add("Fossil fuel"     to "الوقود الأحفوري" )
        wordList.add("Energy"          to "طاقة" )
        wordList.add("Unemployment"    to "بطالة" )
        wordList.add("Landscape"       to "مشهد – منظر طبيعي" )
        wordList.add("Literacy"        to "محو الأمية" )
        wordList.add("Malnutrition"    to "سوء التغذية" )
        wordList.add("Migration"       to "هجرة" )
        wordList.add("Radiation"      to "إشعاع" )
        wordList.add("Nuclear energy" to "طاقة نووية" )
        wordList.add("Crater"         to "فوهة البركان" )
        wordList.add("Sand dunes"     to "الكثبان الرملية" )
        wordList.add("Trade" to "تجارة")
        wordList.add("Urban" to "حضري")
        wordList.add("Rural" to "قروي – ريفي")
        wordList.add("Economy" to "اقتصاد")
        wordList.add("Poverty" to "فقر")
        wordList.add("Slum" to "أحياء فقيرة")
        wordList.add("Life expectancy" to "متوسط العمر المتوقع")
        wordList.add("Attic" to "غرفة علوية، سندرة")
        wordList.add("Bathroom" to "حمّام")
        wordList.add("Bedroom" to "غرفة النوم")
        wordList.add("Cellar" to "سرداب")
        wordList.add("Conservatory" to "معهد الموسيقى")
        wordList.add("Dining room" to "غرفة الطعام")
        wordList.add("Hall" to "صالة")
        wordList.add("Kitchen" to "مطبخ")
        wordList.add("ground floor" to "الطابق الارضي")
        wordList.add("Lavatory" to "مرحاض")
        wordList.add("Livingroom" to "غرفة المعيشة")
        wordList.add("Loft" to "غرفة علوية")
        wordList.add("Lounge" to "غرفة الاستقبال")
        wordList.add("Shower room" to "غرفة استحمام")
        wordList.add("Study" to "دراسة")
        wordList.add("Sitting room" to "غرفة الجلوس")
        wordList.add("Toilet" to "مرحاض) تواليت(")
        wordList.add("Utility room" to "غرفة المرافق")
        wordList.add("Wc" to "مرحاض – دورة مياه")
        wordList.add("Backdoor" to "الباب الخلفي")
        wordList.add("Bath" to "حمام")
        wordList.add("Ceiling" to "سقف")
        wordList.add("Central heating" to "التدفئة المركزية")
        wordList.add("Chimney" to "مدخنة")
        wordList.add("Door" to "باب")
        wordList.add("Doorbell" to "جرس")
        wordList.add("Drainpipe" to "أنبوب التصريف")
        wordList.add("Double glazing" to "زجاج مزدوج")
        wordList.add("Fireplace" to "موقد- مدفأة")
        wordList.add("Floor" to "أرضية")
        wordList.add("Frontdoor" to "الباب الامامي")
        wordList.add("Guttering" to "مزراب")
        wordList.add("Roof" to "سطح")
        wordList.add("Shower" to "استحمام – دش")
        wordList.add("Stairs" to "درج")
        wordList.add("Staircase" to "سُّلّم")
        wordList.add("Window" to "نافذة")
        wordList.add("Downstairs" to "طابق سفلي")
        wordList.add("Upstairs" to "طابق علوي")
        wordList.add("Gas bill" to "فاتورة الغاز")
        wordList.add("Electricity bill" to "فاتورة الكهرباء")
        wordList.add("Telephone bill" to "فاتورة الهاتف")
        wordList.add("Water bill" to "فاتورة الماء")
        wordList.add("Chores" to "الأعمال المنزلية")
        wordList.add("The backgarden" to "الحديقة الخلفية")
        wordList.add("Clothesline" to "حبل الغسيل")
        wordList.add("Drain" to "مصرف مياه ) بالوعة (")
        wordList.add("Drive" to "قيادة أو محرك")
        wordList.add("Dustbin" to "صندوق القمامة")
        wordList.add("A basket of flowers" to "سلة من الزهور")
        wordList.add("Flowerpot" to "إناء الزهور- أصيص")
        wordList.add("Flowers" to "زهور")
        wordList.add("The frontgarden" to "الحديقة الأمامية")
        wordList.add("Garage" to "مرآب، جراج")
        wordList.add("Lawn furniture" to "أثاث الحديقة")
        wordList.add("Gate" to "بوابة")
        wordList.add("Gravel" to "حصى")
        wordList.add("Greenhouse" to "بيت زجاجي، صوبة زراعية")
        wordList.add("Hanging basket" to "سلة معلقة")
        wordList.add("Hedge" to "سياج")
        wordList.add("Lawn" to "بستان")
        wordList.add("Letterbox" to "صندوق الرسائل")
        wordList.add("Logs" to "جذوع الأشجار")
        wordList.add("Orchard" to "بستان")
        wordList.add("Path" to "طريق")
        wordList.add("Patio" to "فناء – باحة")
        wordList.add("Plants" to "نباتات")
        wordList.add("Pond" to "بركة")
        wordList.add("Shed" to "كوخ – سقيفة")
        wordList.add("Pool" to "بركة سباحة")
        wordList.add("Swing" to "أرجوحة")
        wordList.add("Trampoline" to "منصة القفز")
        wordList.add("Vegetablegarden" to "حديقة خضروات")
        wordList.add("Weeds" to "الأعشاب الضارة")
        wordList.add("Mow the lawn" to "جّزّالعشب – قص العشب")
        wordList.add("Axe" to "فأس")
        wordList.add("Fork" to "شوكة")
        wordList.add("Rake" to "مجرفة – أداة لجمع العشب")
        wordList.add("Hosepipe" to "خرطوم سقاية")
        wordList.add("Lawnmower" to "جزارة عشب")
        wordList.add("Hoe" to "مجرفة")
        wordList.add("Scissors" to "مقص")
        wordList.add("Shears" to "مقص الزرع")
        wordList.add("Spade" to "مجرفة – مجراف")
        wordList.add("Trowel" to "جاروف")
        wordList.add("Watering can" to "رشاش مياه")
        wordList.add("Wheelbarrow" to "عربة يدوية")
        wordList.add("Fridge – Refrigerator" to "ثلاجة – بَرّاد")
        wordList.add("Coffee pot" to "وعاء القهوة")
        wordList.add("Cooker" to "جهاز طبخ")
        wordList.add("Dishwasher" to "غسالة صحون")
        wordList.add("Freezer" to "مجمد")
        wordList.add("Kettle" to "غلاية")
        wordList.add("Oven" to "فرن")
        wordList.add("Stove" to "موقد")
        wordList.add("Toaster" to "محمصة خبز")
        wordList.add("Washing machine" to "غسالة")
        wordList.add("Bottle opener" to "فّتّاحة زجاجات")
        wordList.add("Chopping board" to "لوح التقطيع – لوح فرم")
        wordList.add("Colander" to "مصفاة")
        wordList.add("Corkscrew" to "مفتاح")
        wordList.add("Frying pan" to "مقلاة")
        wordList.add("Cheese grater" to "مبشرة جبن")
        wordList.add("Juicer" to "عصارة")
        wordList.add("Tinfoil" to "رقائق القصدير")
        wordList.add("Kitchenscales" to "ميزان المطبخ")
        wordList.add("Ladle" to "مغرفة")
        wordList.add("Mixing bowl" to "وعاء خلط")
        wordList.add("Evidence" to "إثبات - دليل")
        wordList.add("Ovengloves" to "قفازات الفرن")
        wordList.add("Rollingpin" to "مرقاق العجين")
        wordList.add("Saucepan" to "ِقِدر الحساء")
        wordList.add("Sponge" to "إسفنجة")
        wordList.add("Sieve" to "مُنخل – غربال")
        wordList.add("Tin opener" to "فتاحة علب")
        wordList.add("Tongs" to "ملقط")
        wordList.add("Tray" to "صينية")
        wordList.add("Whisk" to "مخفقة بيض")
        wordList.add("Wooden spoon" to "ملعقة خشب")
        wordList.add("Knife" to "سكين")
        wordList.add("Fork" to "شوكة")
        wordList.add("Spoon" to "ملعقة")
        wordList.add("Dessert spoon" to "ملعقة الحلوى")
        wordList.add("Soup spoon" to "ملعقة الحساء")
        wordList.add("Tablespoon" to "ملعقة الطعام")
        wordList.add("Teaspoon" to "ملعقة الشاي")
        wordList.add("Steak knife" to "سكين لحم")
        wordList.add("Chopsticks" to "عيدان الطعام")
        wordList.add("Cup" to "كوب – فنجان")
        wordList.add("Bowl" to "زبدية , سلطانية")
        wordList.add("Crockery" to "آنية فّخّارية")
        wordList.add("Glass" to "كأس زجاجي")
        wordList.add("Jar" to "جرّة")
        wordList.add("Jug" to "إبريق")
        wordList.add("Mug" to "كوز – قدح")
        wordList.add("Plate" to "طبق")
        wordList.add("Saucer" to "طبق الفنجان")
        wordList.add("Sugarbowl" to "وعاء السكر – سّكّريّة")
        wordList.add("Teapot" to "إبريق الشاي")
        wordList.add("Wineglass" to "كأس خمر")
        wordList.add("Bin" to "صندوق")
        wordList.add("Clear plastic" to "بلاستيك شفاف")
        wordList.add("Cookbook" to "كتاب الطبخ")
        wordList.add("Dishcloth" to "ليفة الصحون")
        wordList.add("Sink" to "مغسلة – حوض المطبخ")
        wordList.add("Grill" to "شواية")
        wordList.add("Kitchen table" to "طاولة المطبخ")
        wordList.add("Plug" to "سدادة")
        wordList.add("Tea Towel" to "منشفة الشاي")
        wordList.add("Shelf" to "رف")
        wordList.add("Towel rack" to "حامل مناشف")
        wordList.add("Tablecloth" to "مفرش الطاولة")
        wordList.add("Washing up liquid" to "سائل غسل الصحون")
        wordList.add("Wash" to "يغسل")
        wordList.add("Wash the dishes" to "يغسل الصحون")
        wordList.add("Cleans the table" to "ينظف الطاولة")
        wordList.add("Set the table" to "يجهز الطاولة")
        wordList.add("Armchair" to "كرسي ذو ذراعين")
        wordList.add("Bed" to "سرير")
        wordList.add("Bedside table" to "طاولة السرير")
        wordList.add("Bookcase" to "خزانة كتب")
        wordList.add("Bookshelf" to "رف للكتب")
        wordList.add("Chair" to "كرسي")
        wordList.add("Chest of drawers" to "خزانة الأدراج")
        wordList.add("Clock" to "ساعة حائط")
        wordList.add("Coat rack" to "رف المعطف – شمّاعة")
        wordList.add("Coffee table" to "طاولة صغيرة")
        wordList.add("Cupboard" to "خزانة – دولاب")
        wordList.add("Desk" to "مكتب – منضدة")
        wordList.add("Double bed" to "سرير مزدوج")
        wordList.add("Dressing table" to "طاولة الزينة")
        wordList.add("Double room" to "غرفة مزدوجة")
        wordList.add("Filing cabinet" to "خزانة الملفات")
        wordList.add("Mirror" to "مرآة")
        wordList.add("Piano" to "بيانو")
        wordList.add("Sideboard" to "بوفيه")
        wordList.add("Single bed" to "سرير مفرد")
        wordList.add("Sofa" to "أريكة – كنبة")
        wordList.add("Sofa bed" to "أريكة يمكن تحويلها إلى سرير")
        wordList.add("Stool" to "مقعد")
        wordList.add("Table" to "طاولة")
        wordList.add("Wardrobe" to "خزانة الملابس")
        wordList.add("Alarm clock" to "ساعة المنبه")
        wordList.add("Bathroom scales" to "ميزان الحمام")
        wordList.add("Blue-Ray player" to "جهاز تشغيل أقراص ليزرية")
        wordList.add("CD player" to "جهاز تشغيل سي دي")
        wordList.add("DVD player" to "قارئ أقراص دي في دي")
        wordList.add("Electric stove" to "موقد كهربائي – فرن كهربائي")
        wordList.add("Games console" to "وحدة التحكم في الألعاب")
        wordList.add("Gas stove" to "موقد الغاز")
        wordList.add("Vacuum cleaner" to "مكنسة كهربائية")
        wordList.add("Iron" to "مكواة")
        wordList.add("Lamp" to "مصباح")
        wordList.add("Radiator" to "مشعاع – مدفأة")
        wordList.add("Radio" to "مذياع – راديو")
        wordList.add("Record player" to "مشغل أسطوانات")
        wordList.add("Spin dryer" to "نشّافة , مجفف ملابس")
        wordList.add("Stereo" to "جهاز تكبير الصوت")
        wordList.add("Telephone" to "تلفون – هاتف")
        wordList.add("Television" to "تلفاز")
        wordList.add("Washing machine" to "غسالة كهربائية")
        wordList.add("Blanket" to "غطاء – بطانية")
        wordList.add("Blinds" to "ستائر")
        wordList.add("Carpet" to "سجادة")
        wordList.add("Curtains" to "ستائر")
        wordList.add("Cushion" to "وسادة")
        wordList.add("Duvet" to "لحاف")
        wordList.add("Mattress" to "ِفِراش – مرتبة")
        wordList.add("Pillow" to "وسادة - مخدة")
        wordList.add("Pillowcase" to "غطاء الوسادة")
        wordList.add("Rug" to "بساط")
        wordList.add("Sheet" to "صفحة – ورقة")
        wordList.add("Tablecloth" to "مفرش المائدة")
        wordList.add("Towel" to "منشفة")
        wordList.add("Wallpaper" to "ورق جدران - ورق الحائط")
        wordList.add("Bath" to "مغطس – بانيو")
        wordList.add("Bin" to "سلة مهملات")
        wordList.add("Broom" to "مكنسة – مقشة")
        wordList.add("Bucket" to "سطل – دلو")
        wordList.add("Coat hanger" to "شمّاعة المعاطف")
        wordList.add("Cold tap" to "صنبور الماء البارد")
        wordList.add("Doorhandle" to "مقبض الباب")
        wordList.add("Doorknob" to "مقابض الأبواب")
        wordList.add("Doormat" to "ممسحة الأرجل")
        wordList.add("Dustbin" to "صندوق القمامة")
        wordList.add("Dustpan and brush" to "مكنسة وجاروف")
        wordList.add("Flannel" to "الفانيلا")
        wordList.add("Fuse box" to "صندوق الكهرباء")
        wordList.add("Hot tap" to "صنبور الماء الساخن")
        wordList.add("House plant" to "نبات منزلي")
        wordList.add("Ironing board" to "طاولة الكيّ")
        wordList.add("Lamp shade" to "مظلة المصباح")
        wordList.add("Light switch" to "مفتاح ضوء كهرباء")
        wordList.add("Mop" to "ممسحة")
        wordList.add("Ornament" to "زينة – زخرفة")
        wordList.add("Painting" to "لوحة")
        wordList.add("Picture" to "صورة")
        wordList.add("Power socket" to "مأخذ او مقبس الكهرباء")
        wordList.add("Drain" to "بالوعة")
        wordList.add("Poster" to "مُلصق")
        wordList.add("Sponge" to "إسفنج")
        wordList.add("Tap" to "صنبور - حنفية")
        wordList.add("Torch" to "شعلة")
        wordList.add("Vase" to "مزهرية")
        wordList.add("Wastepaper basket" to "سلة النفايات الورقية")
        wordList.add("Battery" to "بطارية")
        wordList.add("Candle" to "شمعة")
        wordList.add("Cotton" to "قطن")
        wordList.add("Envelope" to "ظرف")
        wordList.add("Fireplace" to "شعلة للغاز أو المدفأة")
        wordList.add("Fuse" to "فتيل")
        wordList.add("Glue" to "غراء أو صمغ")
        wordList.add("Light bulb" to "مصباح أو لمبة")
        wordList.add("Lighter" to "شعلة أو قداحة")
        wordList.add("Match" to "كبريت")
        wordList.add("Needle" to "إبرة")
        wordList.add("Pin" to "دبوس")
        wordList.add("Scissors" to "مقص")
        wordList.add("Sellotape" to "شريط لاصق")
        wordList.add("Stamps" to "طوابع")
        wordList.add("Pen" to "قلم")
        wordList.add("Pencil" to "قلم رصاص")
        wordList.add("Tissue paper" to "مناديل ورقية")
        wordList.add("Toilet paper" to "ورق تواليت")
        wordList.add("Toothpaste" to "معجون أسنان")
        wordList.add("Toothbrush" to "فرشاة الأسنان")
        wordList.add("Writing paper" to "ورق كتابة")
        wordList.add("Garbage bag" to "كيس قمامة")
        wordList.add("Bleach" to "تبييض الملابس")
        wordList.add("Detergent" to "منظفات")
        wordList.add("Disinfectant" to "مطهر")
        wordList.add("Trash bag" to "كيس النفايات")
        wordList.add("Duster" to "منفضة غبار")
        wordList.add("Fabric softener" to "منعم غسيل")
        wordList.add("Floor cloth" to "ممسحة أرض")
        wordList.add("Furniture polish" to "مادة لتلميع الأثاث")
        wordList.add("Vacuum cleaner bag" to "كيس المكنسة الكهربائية")
        wordList.add("Shoe polish" to "مادة لتلميع الأحذية")
        wordList.add("Soap" to "صابون")
        wordList.add("Washing powder" to "مسحوق غسيل")
        wordList.add("By bicycle" to "بالدراجة")
        wordList.add("By boat" to "بالقارب")
        wordList.add("By bus" to "بالباص أو بالحافلة")
        wordList.add("By car" to "بالسيارة")
        wordList.add("By coach" to "بالحافلة")
        wordList.add("By ferry" to "بالعبّارة")
        wordList.add("By motorcycle" to "بالدراجة النارية")
        wordList.add("By plane" to "بالطائرة")
        wordList.add("By train" to "بالقطار")
        wordList.add("On foot" to "مشيا على الأقدام")
        wordList.add("Box office" to "شباك تذاكر")
        wordList.add("Travel agent" to "وكيل سفر")
        wordList.add("Brochure" to "كتيب – نشرة")
        wordList.add("Price" to "سعر أو ثمن")
        wordList.add("Fare" to "أجرة")
        wordList.add("Ticket" to "تذكرة")
        wordList.add("Booking" to "حجز")
        wordList.add("Reservation" to "حجز")
        wordList.add("Passenger" to "راكب")
        wordList.add("Destination" to "وجهة")
        wordList.add("Itinerary" to "خط سير الرحلة")
        wordList.add("Journey" to "رحلة")
        wordList.add("Travel insurance" to "تأمين للسفر")
        wordList.add("Holiday" to "عطلة")
        wordList.add("Sightseeing" to "مشاهدة معالم المدينة")
        wordList.add("Business trip" to "رحلة عمل")
        wordList.add("To book" to "أن يحجز")
        wordList.add("To cancel a booking" to "لإلغاء الحجز")
        wordList.add("Arrive" to "يصل")
        wordList.add("Leave" to "يغادر")
        wordList.add("Depart" to "يغادر")
        wordList.add("Travel" to "يسافر")
        wordList.add("Visit" to "يزور")
        wordList.add("Cancellation" to "إلغاء")
        wordList.add("Customs" to "جمارك")
        wordList.add("Delay" to "تأخير")
        wordList.add("Luggage" to "الامتعة")
        wordList.add("Map" to "خارطة")
        wordList.add("Passport control" to "مراقبة الجوازات")
        wordList.add("Suitcase" to "حقيبة سفر")
        wordList.add("Cancelled" to "ألغى")
        wordList.add("Delayed" to "متأخر")
        wordList.add("Bypass" to "طريق جانبي")
        wordList.add("Lane" to "حارة – ممر")
        wordList.add("Dual carriage way" to "طريق مزدوج للسيارات")
        wordList.add("Main road" to "طريق رئيسي")
        wordList.add("Motorway" to "طريق سريعة")
        wordList.add("One-way-street" to "شارع باتجاه واحد")
        wordList.add("Ringroad" to "طريق دائري")
        wordList.add("Road" to "طريق أو شارع")
        wordList.add("Tollroad" to "طريق برسم مرور")
        wordList.add("Corner" to "زاوية, ركن")
        wordList.add("Crossroads" to "تقاطع طرق")
        wordList.add("Kerb" to "رصيف")
        wordList.add("Fork, crossway" to "مفترق طرق")
        wordList.add("Junction" to "تقاطع")
        wordList.add("Parking spaces" to "مكان وقوف السيارات")
        wordList.add("Level crossing" to "تقاطع – معابر السكة الحديدية")
        wordList.add("Pavement" to "رصيف الشارع")
        wordList.add("Crosswalk" to "ممر مشاة")
        wordList.add("Road sign" to "لافتة طريق")
        wordList.add("Roadside" to "طرف - جانب الطريق")
        wordList.add("Roadworks" to "أعمال صيانة الطرق")
        wordList.add("Roundabout" to "دوّار")
        wordList.add("Services" to "خدمات – مرافق")
        wordList.add("Signpost" to "لافتة")
        wordList.add("Speedlimit" to "الحد الأقصى للسرعة")
        wordList.add("T-Junction" to "تقاطع طرق على شكل حرف T")
        wordList.add("Toll" to "ضريبة طرق")
        wordList.add("Trafficlight" to "إشارة مرور")
        wordList.add("Turning" to "دوران – منعطف")
        wordList.add("Accident" to "حادث")
        wordList.add("Breakdown" to "تعطل– انهيار")
        wordList.add("Breathalyser" to "جهاز قياس مستوى الكحول للسائق")
        wordList.add("Jack" to "رافعة سيارات")
        wordList.add("Jump leads" to "أسلاك أو وصلة بطارية السيارة")
        wordList.add("Flat tire" to "إطار فارغ – عجلة مثقوبة")
        wordList.add("Fog" to "ضباب")
        wordList.add("Icy road" to "طريق جليدي")
        wordList.add("Puncture" to "ثقب أو خرم في العجلة")
        wordList.add("Speeding fine" to "غرامة تجاوز السرعة")
        wordList.add("Spray" to "رشاش")
        wordList.add("Traffic jam" to "ازدحام مروري")
        wordList.add("Crash" to "تحّطّم – اصطدام")
        wordList.add("Disaster" to "كارثة")
        wordList.add("Slide" to "ينزلق")
        wordList.add("Engine stop" to "توقف المحرك")
        wordList.add("Swerve" to "انحراف")
        wordList.add("Driving instructor" to "معلم سياقة")
        wordList.add("Driving lesson" to "درس سياقة")
        wordList.add("Driving licence" to "شهادة أو رخصة قيادة")
        wordList.add("Driving school" to "مدرسة لتعليم القيادة")
        wordList.add("Driving test" to "امتحان سياقة")
        wordList.add("Learner driver" to "سائق قيد التمرين")
        wordList.add("Failed to driving test" to "فشل في اختبار القيادة")
        wordList.add("Passed the driving test" to "اجتاز اختبار القيادة")
        wordList.add("Car park" to "موقف سيارات")
        wordList.add("Parking for disabled" to "موقف سيارات للمعاقين")
        wordList.add("Multi storey car park" to "موقف سيارات متعدد الطوابق")
        wordList.add("To stop the car" to "لإيقاف السيارة")
        wordList.add("Parking meter" to "عداد مواقف السيارات")
        wordList.add("Parking space" to "مساحة لوقوف السيارات")
        wordList.add("Parking ticket" to "تذكرة وقوف السيارات")
        wordList.add("Traffic warden" to "مأمور مرور")
        wordList.add("Car wash" to "مغسلة سيارات")
        wordList.add("Diesel" to "ديزل")
        wordList.add("Oil" to "نفط")
        wordList.add("Petrol" to "بنزين")
        wordList.add("Fuel pump" to "مضخة وقود")
        wordList.add("Petrol station" to "محطة وقود")
        wordList.add("Unleaded fuel" to "وقود خالي من الرصاص")
        wordList.add("Bike - Bicycle" to "دراجة")
        wordList.add("Van" to "فان عربة – شاحنة")
        wordList.add("Bus" to "حافلة أو باص")
        wordList.add("Car" to "سيارة")
        wordList.add("Caravan" to "بيت نقّاّل - مقطورة")

        wordList.add(""   to "" )
        wordList.add(""   to "" )
        wordList.add(""   to "" )
        wordList.add(""   to "" )
        wordList.add(""   to "" )
        wordList.add(""   to "" )
        wordList.add(""   to "" )
        wordList.add(""   to "" )
        wordList.add(""   to "" )
        wordList.add(""   to "" )
        wordList.add(""   to "" )
        wordList.add(""   to "" )
        wordList.add(""   to "" )
        wordList.add(""   to "" )
        wordList.add(""   to "" )
        wordList.add(""   to "" )
        wordList.add(""   to "" )
        wordList.add(""   to "" )
        wordList.add(""   to "" )
        wordList.add(""   to "" )
        wordList.add(""   to "" )
        wordList.add(""   to "" )
        wordList.add(""   to "" )
        wordList.add(""   to "" )
        wordList.add(""   to "" )

    }
}
